CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
    CREATE TYPE user_role AS ENUM ('customer', 'restaurant', 'driver', 'admin');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'account_status') THEN
    CREATE TYPE account_status AS ENUM ('active', 'suspended');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name VARCHAR(120) NOT NULL,
  alias TEXT,
  email VARCHAR(150) NOT NULL,
  real_email TEXT,
  password_hash TEXT NOT NULL,
  role user_role NOT NULL,
  status account_status NOT NULL DEFAULT 'active',
  address TEXT,
  lat NUMERIC(9,6),
  lng NUMERIC(9,6),
  calle TEXT,
  numero TEXT,
  postal_code TEXT,
  colonia TEXT,
  estado TEXT,
  ciudad TEXT,
  home_lat DOUBLE PRECISION,
  home_lng DOUBLE PRECISION,
  email_verified BOOLEAN NOT NULL DEFAULT false,
  email_verify_token TEXT,
  email_verify_expires TIMESTAMPTZ,
  google_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS restaurants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(140) NOT NULL,
  category VARCHAR(80) NOT NULL,
  address TEXT,
  is_open BOOLEAN NOT NULL DEFAULT true,
  is_active BOOLEAN NOT NULL DEFAULT true,
  manual_open_override BOOLEAN DEFAULT NULL,
  profile_photo TEXT,
  lat NUMERIC(9,6),
  lng NUMERIC(9,6),
  postal_code TEXT,
  colonia TEXT,
  estado TEXT,
  ciudad TEXT,
  home_lat DOUBLE PRECISION,
  home_lng DOUBLE PRECISION,
  rating_avg NUMERIC(3,2) DEFAULT NULL,
  rating_count INT NOT NULL DEFAULT 0,
  prep_time_estimate_s INTEGER NOT NULL DEFAULT 600,
  last_prep_time_s INTEGER,
  prep_estimate_updated_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS menu_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  name VARCHAR(140) NOT NULL,
  description TEXT,
  price_cents INT NOT NULL,
  is_available BOOLEAN NOT NULL DEFAULT true,
  image_url TEXT,
  pkg_units SMALLINT NOT NULL DEFAULT 1,
  pkg_volume_liters NUMERIC(6,3) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS driver_profiles (
  user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  driver_number BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  vehicle_type VARCHAR(50),
  is_verified BOOLEAN NOT NULL DEFAULT false,
  is_available BOOLEAN NOT NULL DEFAULT false,
  last_lat NUMERIC(9,6),
  last_lng NUMERIC(9,6),
  disconnect_penalties INTEGER NOT NULL DEFAULT 0,
  bag_capacity_liters NUMERIC(6,2) NOT NULL DEFAULT 25,
  total_rebalances INT NOT NULL DEFAULT 0,
  total_releases INT NOT NULL DEFAULT 0,
  total_cancels INT NOT NULL DEFAULT 0,
  total_expires INT NOT NULL DEFAULT 0,
  session_rebalances INT NOT NULL DEFAULT 0,
  session_releases INT NOT NULL DEFAULT 0,
  session_cancels INT NOT NULL DEFAULT 0,
  session_expires INT NOT NULL DEFAULT 0,
  session_started_at TIMESTAMPTZ,
  rating_avg NUMERIC(3,2) DEFAULT NULL,
  rating_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID NOT NULL REFERENCES users(id),
  restaurant_id UUID NOT NULL REFERENCES restaurants(id),
  driver_id UUID REFERENCES users(id),
  last_driver_id UUID REFERENCES users(id) ON DELETE SET NULL,
  disputed_by UUID REFERENCES users(id) ON DELETE SET NULL,
  status VARCHAR(30) NOT NULL,
  total_cents INT NOT NULL,
  service_fee_cents INTEGER NOT NULL DEFAULT 0,
  delivery_fee_cents INTEGER NOT NULL DEFAULT 0,
  restaurant_fee_cents INTEGER NOT NULL DEFAULT 0,
  tip_cents INTEGER NOT NULL DEFAULT 0,
  delivered_tip_cents INTEGER NOT NULL DEFAULT 0,
  payment_method TEXT NOT NULL DEFAULT 'cash' CHECK (payment_method IN ('cash', 'card', 'spei')),
  delivery_address TEXT NOT NULL,
  delivery_lat DOUBLE PRECISION,
  delivery_lng DOUBLE PRECISION,
  restaurant_lat NUMERIC(9,6),
  restaurant_lng NUMERIC(9,6),
  estimated_volume_liters NUMERIC(8,3) NOT NULL DEFAULT 0,
  suggestion_text TEXT,
  suggestion_status VARCHAR(20) NOT NULL DEFAULT 'none',
  driver_note TEXT,
  restaurant_note TEXT,
  accepted_at TIMESTAMPTZ,
  preparing_at TIMESTAMPTZ,
  ready_at TIMESTAMPTZ,
  picked_up_at TIMESTAMPTZ,
  delivered_at TIMESTAMPTZ,
  cancelled_at TIMESTAMPTZ,
  offer_cooldown_triggered BOOLEAN NOT NULL DEFAULT false,
  reconnect_deadline TIMESTAMPTZ,
  prep_started_at TIMESTAMPTZ,
  kitchen_estimated_ready TIMESTAMPTZ,
  pickup_wait_s INTEGER NOT NULL DEFAULT 0,
  last_transferred_at TIMESTAMPTZ,
  assignment_score DOUBLE PRECISION,
  route_distance_km DOUBLE PRECISION,
  is_disputed BOOLEAN NOT NULL DEFAULT false,
  disputed_until TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS order_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  menu_item_id UUID REFERENCES menu_items(id) ON DELETE SET NULL,
  quantity INT NOT NULL,
  unit_price_cents INT NOT NULL
);

CREATE TABLE IF NOT EXISTS order_driver_offers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  driver_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  wait_until TIMESTAMPTZ,
  bag_overflow_pct SMALLINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(order_id, driver_id)
);

CREATE TABLE IF NOT EXISTS restaurant_schedules (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  day_of_week SMALLINT NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
  opens_at TIME,
  closes_at TIME,
  is_closed BOOLEAN NOT NULL DEFAULT false,
  UNIQUE(restaurant_id, day_of_week)
);

CREATE TABLE IF NOT EXISTS order_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  sender_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  text TEXT NOT NULL CHECK (char_length(text) <= 500),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS order_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  reporter_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  reporter_role VARCHAR(20) NOT NULL,
  reason VARCHAR(80) NOT NULL DEFAULT 'general',
  text TEXT NOT NULL,
  reviewed BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS order_complaints (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  customer_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS order_ratings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  customer_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  driver_id UUID REFERENCES users(id) ON DELETE SET NULL,
  restaurant_stars SMALLINT NOT NULL CHECK (restaurant_stars BETWEEN 1 AND 5),
  driver_stars SMALLINT CHECK (driver_stars BETWEEN 1 AND 5),
  comment TEXT,
  restaurant_rates_driver SMALLINT CHECK (restaurant_rates_driver BETWEEN 1 AND 5),
  driver_rates_restaurant SMALLINT CHECK (driver_rates_restaurant BETWEEN 1 AND 5),
  driver_comment TEXT,
  restaurant_comment TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(order_id)
);

CREATE TABLE IF NOT EXISTS road_zones (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  radius_m INTEGER NOT NULL DEFAULT 100,
  type VARCHAR(20) NOT NULL,
  estimated_hours INTEGER NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  active BOOLEAN NOT NULL DEFAULT true,
  confirmed BOOLEAN NOT NULL DEFAULT false,
  created_by UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS zone_votes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  zone_id UUID NOT NULL REFERENCES road_zones(id) ON DELETE CASCADE,
  driver_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  vote VARCHAR(10) NOT NULL CHECK (vote IN ('confirm', 'dismiss')),
  voted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(zone_id, driver_id)
);

CREATE TABLE IF NOT EXISTS zone_pending_edits (
  zone_id UUID PRIMARY KEY REFERENCES road_zones(id) ON DELETE CASCADE,
  type VARCHAR(20),
  estimated_hours INTEGER,
  suggested_by UUID REFERENCES users(id) ON DELETE SET NULL,
  confirm_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS road_preferences (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  driver_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  way_id VARCHAR(30) NOT NULL,
  preference VARCHAR(20) NOT NULL CHECK (preference IN ('preferred', 'difficult', 'avoid')),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(driver_id, way_id)
);

CREATE TABLE IF NOT EXISTS impassable_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  way_id VARCHAR(30) NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  description TEXT,
  estimated_duration VARCHAR(20) NOT NULL CHECK (estimated_duration IN ('days', 'weeks', 'months', 'permanent')),
  confirmed BOOLEAN NOT NULL DEFAULT false,
  consensus_duration VARCHAR(20),
  reported_by UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS impassable_confirmations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  way_id VARCHAR(30) NOT NULL,
  confirmed_by UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  estimated_duration VARCHAR(20) NOT NULL CHECK (estimated_duration IN ('days', 'weeks', 'months', 'permanent')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(way_id, confirmed_by)
);

CREATE TABLE IF NOT EXISTS engine_params (
  key VARCHAR(80) PRIMARY KEY,
  value DOUBLE PRECISION NOT NULL,
  description TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by UUID REFERENCES users(id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_role_key ON users(email, role);
CREATE UNIQUE INDEX IF NOT EXISTS users_real_email_role_idx ON users(real_email, role) WHERE real_email IS NOT NULL;
CREATE INDEX IF NOT EXISTS users_google_id_idx ON users(google_id) WHERE google_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_driver ON orders(driver_id);
CREATE INDEX IF NOT EXISTS idx_orders_restaurant ON orders(restaurant_id);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_status_active ON orders(status) WHERE status NOT IN ('delivered', 'cancelled');
CREATE INDEX IF NOT EXISTS idx_orders_driver_id ON orders(driver_id) WHERE driver_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_orders_last_driver ON orders(last_driver_id) WHERE last_driver_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_orders_reconnect ON orders(reconnect_deadline) WHERE reconnect_deadline IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_orders_kitchen_ready ON orders(kitchen_estimated_ready) WHERE kitchen_estimated_ready IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_orders_disputed ON orders(disputed_until) WHERE is_disputed = true;

CREATE INDEX IF NOT EXISTS idx_order_driver_offers_order ON order_driver_offers(order_id);
CREATE INDEX IF NOT EXISTS idx_order_driver_offers_driver ON order_driver_offers(driver_id);
CREATE INDEX IF NOT EXISTS idx_offers_wait ON order_driver_offers(driver_id, wait_until) WHERE wait_until IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_offers_order_status ON order_driver_offers(order_id, status);
CREATE INDEX IF NOT EXISTS idx_offers_order_wait ON order_driver_offers(order_id, wait_until) WHERE status IN ('rejected', 'expired', 'released');

CREATE INDEX IF NOT EXISTS idx_restaurant_sched ON restaurant_schedules(restaurant_id, day_of_week);
CREATE INDEX IF NOT EXISTS idx_messages_order ON order_messages(order_id, created_at);
CREATE INDEX IF NOT EXISTS idx_reports_order ON order_reports(order_id);
CREATE INDEX IF NOT EXISTS idx_reports_unreviewed ON order_reports(reviewed) WHERE reviewed = false;
CREATE INDEX IF NOT EXISTS idx_ratings_restaurant ON order_ratings(restaurant_id);
CREATE INDEX IF NOT EXISTS idx_ratings_driver ON order_ratings(driver_id);
CREATE INDEX IF NOT EXISTS idx_ratings_customer ON order_ratings(customer_id);
CREATE INDEX IF NOT EXISTS idx_road_zones_expires ON road_zones(expires_at) WHERE active = true;
CREATE INDEX IF NOT EXISTS idx_zone_votes_zone ON zone_votes(zone_id);
CREATE INDEX IF NOT EXISTS idx_impassable_way ON impassable_reports(way_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_impassable_one_per_way ON impassable_reports(way_id) WHERE confirmed = false;

CREATE OR REPLACE FUNCTION set_accepted_at()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'assigned' AND OLD.status != 'assigned' AND NEW.accepted_at IS NULL THEN
    NEW.accepted_at = NOW();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_set_accepted_at ON orders;
CREATE TRIGGER trg_set_accepted_at
  BEFORE UPDATE ON orders
  FOR EACH ROW EXECUTE FUNCTION set_accepted_at();

INSERT INTO engine_params (key, value, description) VALUES
  ('offer_timeout_s', 60, 'Segundos antes de expirar una oferta sin respuesta'),
  ('cooldown_s', 300, 'Penalización en segundos tras rechazar o expirar oferta'),
  ('max_active_orders_per_driver', 4, 'Límite de pedidos simultáneos por driver'),
  ('transfer_min_gain_s', 10, 'Ganancia mínima en segundos para aplicar rebalanceo'),
  ('transfer_cooldown_s', 60, 'Tiempo mínimo entre transferencias del mismo pedido'),
  ('reconnect_window_s', 600, 'Ventana en segundos para que un driver reconecte tras desconexión'),
  ('disconnect_penalty_max', 3, 'Penalizaciones acumuladas antes de excluir al driver de asignaciones'),
  ('disconnect_penalty_s', 300, 'Penalización de scoring por cada desconexión previa'),
  ('assignment_retry_base_s', 2, 'Delay base en segundos entre reintentos de asignación'),
  ('assignment_retry_max_s', 60, 'Delay máximo en segundos entre reintentos de asignación'),
  ('max_pickup_radius_km', 5, 'Radio máximo en km para considerar un driver como candidato'),
  ('kitchen_wait_threshold_s', 120, 'Segundos de espera en restaurante que activan sugerencia de ajuste'),
  ('kitchen_estimate_diff_threshold_s', 90, 'Diferencia mínima entre estimado y real para sugerir cambio'),
  ('rebalancer_interval_s', 300, 'Cada cuántos segundos corre el motor de rebalanceo'),
  ('nearby_driver_preference_m', 250, 'Metros de preferencia para drivers cercanos al restaurante'),
  ('assignment_hard_top_k', 5, 'Número máximo de candidatos a evaluar por ronda'),
  ('fairness_penalty_per_order_s', 120, 'Penalización de scoring por pedido activo adicional del driver'),
  ('soft_sla_penalty_factor', 2, 'Multiplicador de penalización por retraso sobre SLA'),
  ('hard_sla_penalty_s', 3000, 'Penalización fija cuando se excede el SLA'),
  ('pickup_proximity_penalty_factor', 0.35, 'Factor de penalización por distancia driver→restaurante'),
  ('max_delivery_time_s', 1800, 'SLA máximo de entrega en segundos (30 min default)'),
  ('transfer_max_route_eta_s', 180, 'ETA de ruta máximo para disparar rebalanceo automático'),
  ('default_bag_capacity_liters', 25, 'Litros de capacidad de mochila si el driver no especificó la suya')
ON CONFLICT (key) DO NOTHING;
